export const PLANS = [
  {
    id: 'essentiel',
    name: 'Essentiel',
    tagline: 'Begin your wardrobe journey',
    monthly: 0,
    yearly: 0,
    features: ['Digital wardrobe up to 40 pieces', '3 AI outfit recommendations / week', 'Weather-aware daily look', 'Community feed access'],
    cta: 'Start free',
  },
  {
    id: 'signature',
    name: 'Signature',
    tagline: 'The complete personal stylist',
    monthly: 29,
    yearly: 290,
    featured: true,
    features: ['Unlimited wardrobe pieces', 'Unlimited AI outfit generation', 'Outfit planner & travel capsules', '3x / Year automated wardrobe audit', 'Priority concierge chat'],
    cta: 'Choose Signature',
  },
  {
    id: 'maison',
    name: 'Maison',
    tagline: 'For those who dress by appointment',
    monthly: 89,
    yearly: 890,
    features: ['Everything in Signature', 'Dedicated human stylist', 'Seasonal wardrobe audit', 'Private retailer access', 'Calendar & EA integrations'],
    cta: 'Choose Maison',
  },
] as const;

export type Plan = (typeof PLANS)[number];

export const HOME = {
  en: {
    heroPrimary: 'Enter the Atelier',
    heroSecondary: 'See what you get',
    stats: [
      { value: 12000, suffix: '+', label: 'Garments catalogued' },
      { value: 94, suffix: '%', label: 'Say they dress with more confidence' },
      { value: 38, suffix: '%', label: 'Average rise in wardrobe use' },
      { value: 4.9, suffix: '/5', label: 'Member rating', decimals: 1 },
    ],
    offer: {
      label: 'What we offer',
      title: 'Four instruments. One impeccable wardrobe.',
      sub: 'Select a pillar to see exactly what it does for you.',
      items: [
        {
          id: 'stylist',
          tab: 'AI Stylist',
          title: 'A stylist that studies you',
          text: 'Vastrié learns your proportions, palette and taste, then composes looks for the weather, the room and the hour.',
          bullets: ['Recommendations by occasion and climate', 'Learns from every look you wear or reject', 'Explains the "why" behind each pairing'],
          image: '/images/hero_fashion_ai_1791120145819.jpg',
          href: '/outfits',
          cta: 'Try the stylist',
        },
        {
          id: 'wardrobe',
          tab: 'Digital Wardrobe',
          title: 'Your closet, catalogued',
          text: 'Photograph a piece once. Fabric, colour, season and care are recorded, and every wear is remembered.',
          bullets: ['Cost-per-wear and utilisation tracking', 'Care reminders and fabric guidance', 'Gaps analysis: what your wardrobe is missing'],
          image: '/images/wardrobe_blazer_navy.jpg',
          href: '/wardrobe',
          cta: 'Open the wardrobe',
        },
        {
          id: 'outfits',
          tab: 'Outfit Planner',
          title: 'Every event, already dressed',
          text: 'Drop events and trips on a timeline. Vastrié proposes complete outfits and a packing capsule for each.',
          bullets: ['Calendar-aware planning', 'Travel capsules that pack in one case', 'Version history for every look'],
          image: '/images/outfit_recommendation_1791120459094.jpg',
          href: '/planner',
          cta: 'Plan your week',
        },
        {
          id: 'discover',
          tab: 'Discover',
          title: 'Curated, never crowded',
          text: 'A restrained feed of pieces that suit your wardrobe and your budget, drawn from houses we trust.',
          bullets: ['Only items that complete a look', 'Private retailer access on Maison', 'Save, compare and move to wishlist'],
          image: '/images/wardrobe_leather_accessories.jpg',
          href: '/discover',
          cta: 'Start discovering',
        },
      ],
    },
    benefits: {
      label: 'What you will get',
      title: 'Outcomes, not features.',
      items: [
        { icon: 'clock', title: 'Ten minutes back every morning', text: 'Open the app, see your look, step out the door.', metric: '-10 min / day' },
        { icon: 'shirt', title: 'A wardrobe that works harder', text: 'Wear the clothes you own, not just the five you like.', metric: '+38% utilisation' },
        { icon: 'tag', title: 'Smarter spending', text: 'Buy only what completes a look. See cost-per-wear fall.', metric: '-27% impulse buys' },
        { icon: 'sparkle', title: 'A signature, not a trend', text: 'A coherent personal style that outlasts the season.', metric: '1 clear identity' },
        { icon: 'shield', title: 'Privacy you can trust', text: 'Your photos and measurements are yours. Export or delete any time.', metric: '2FA + encryption' },
        { icon: 'globe', title: 'Dress for anywhere', text: 'Climate and culture-aware recommendations for every trip.', metric: '190+ cities' },
      ],
    },
    how: {
      label: 'How it works',
      title: 'From first photo to finished look.',
      steps: [
        { n: '01', title: 'Tell us who you are', text: 'A five-minute style profile captures your build, palette, lifestyle and the way you want to be perceived.' },
        { n: '02', title: 'Build your wardrobe', text: 'Photograph your pieces. We tag fabric, colour and season automatically, and flag what is missing.' },
        { n: '03', title: 'Receive your looks', text: 'Every day, and for every event, Vastrié composes outfits from what you own — with reasoning.' },
        { n: '04', title: 'Refine and grow', text: 'Rate looks, add pieces and review monthly reports. The more you wear, the sharper it gets.' },
      ],
    },
    capabilities: {
      label: 'The complete atelier',
      title: 'Every capability you would expect — and then some.',
      sub: 'Twelve considered dimensions of personal styling.',
      open: 'Explore',
    },
    pricing: {
      label: 'Memberships',
      title: 'Transparent. Cancel any time.',
      monthly: 'Monthly',
      yearly: 'Yearly',
      save: 'Save 2 months',
      perMonth: '/ month',
      perYear: '/ year',
      all: 'Compare all plans',
      featured: 'Most chosen',
    },
    proof: {
      label: 'Voices',
      title: 'Worn, trusted, recommended.',
      items: [
        { quote: 'It finally feels like having a stylist who knows my wardrobe better than I do. I stopped second-guessing every morning.', name: 'Julien Marchetti', role: 'Partner, Marchetti & Co.' },
        { quote: 'The travel capsules alone paid for the year. One carry-on, six cities, never underdressed.', name: 'Arnav Kapoor', role: 'Management consultant' },
        { quote: 'The restraint is what sold me. No noise, no trends — just an honest eye on what suits me.', name: 'Théo Lambert', role: 'Architect' },
      ],
    },
    faq: {
      label: 'Questions',
      title: 'Before you begin.',
      items: [
        { q: 'Is Vastrié really free to start?', a: 'Yes. Essentiel is free forever with up to 40 wardrobe pieces and three AI outfit recommendations each week. Upgrade only when you need more.' },
        { q: 'Do I need to photograph my whole wardrobe?', a: 'No. Start with ten pieces you wear most. Vastrié becomes useful immediately and improves as you add more.' },
        { q: 'What happens to my photos and data?', a: 'They are encrypted, never sold, and never used to train models for others. You can export or permanently delete everything from your Account page.' },
        { q: 'Can I cancel at any time?', a: 'Yes — one click from Billing. You keep access until the end of your paid period and your wardrobe stays yours.' },
        { q: 'Is this only for men?', a: 'Vastrié is currently designed around menswear and tailoring. Womenswear is on our roadmap — join the waitlist from your Account.' },
      ],
    },
    cta: {
      title: 'Dress with intention.',
      text: 'Join in under a minute. No card required.',
      primary: 'Enter the Atelier',
      secondary: 'Continue as guest',
    },
    footer: {
      cols: [
        { title: 'Product', links: [['Wardrobe', '/wardrobe'], ['Outfits', '/outfits'], ['Planner', '/planner'], ['Pricing', '/pricing']] },
        { title: 'Discover', links: [['Our story', '#story'], ['Journal', '/feed'], ['Help Center', '/help'], ['Status', '/maintenance']] },
        { title: 'Account', links: [['Login', '/auth'], ['Settings', '/settings'], ['Billing', '/billing'], ['Security', '/settings/security']] },
        { title: 'Legal', links: [['Privacy Policy', '/legal/privacy'], ['Terms of Service', '/legal/terms'], ['Cookie Policy', '/legal/cookies']] },
      ],
      tag: 'The master of personal style.',
    },
  },
  fr: {
    heroPrimary: "Entrer dans l'Atelier",
    heroSecondary: 'Voir ce que vous obtenez',
    stats: [
      { value: 12000, suffix: '+', label: 'Vêtements catalogués' },
      { value: 94, suffix: '%', label: "S'habillent avec plus d'assurance" },
      { value: 38, suffix: '%', label: "Hausse moyenne de l'usage de la garde-robe" },
      { value: 4.9, suffix: '/5', label: 'Note des membres', decimals: 1 },
    ],
    offer: {
      label: 'Ce que nous offrons',
      title: 'Quatre instruments. Une garde-robe impeccable.',
      sub: 'Sélectionnez un pilier pour voir précisément ce qu’il fait pour vous.',
      items: [
        {
          id: 'stylist',
          tab: 'Styliste IA',
          title: 'Un styliste qui vous étudie',
          text: 'Vastrié apprend vos proportions, votre palette et votre goût, puis compose des looks selon la météo, le lieu et l’heure.',
          bullets: ['Recommandations par occasion et climat', 'Apprend de chaque look porté ou refusé', 'Explique le « pourquoi » de chaque association'],
          image: '/images/hero_fashion_ai_1791120145819.jpg',
          href: '/outfits',
          cta: 'Essayer le styliste',
        },
        {
          id: 'wardrobe',
          tab: 'Garde-robe numérique',
          title: 'Votre dressing, catalogué',
          text: 'Photographiez une pièce une fois. Tissu, couleur, saison et entretien sont enregistrés, chaque port est mémorisé.',
          bullets: ['Coût par port et taux d’utilisation', 'Rappels d’entretien et conseils sur les tissus', 'Analyse des manques de votre garde-robe'],
          image: '/images/wardrobe_blazer_navy.jpg',
          href: '/wardrobe',
          cta: 'Ouvrir la garde-robe',
        },
        {
          id: 'outfits',
          tab: 'Planificateur',
          title: 'Chaque événement, déjà habillé',
          text: 'Placez événements et voyages sur une frise. Vastrié propose des tenues complètes et une capsule de voyage.',
          bullets: ['Planification liée au calendrier', 'Capsules de voyage dans une seule valise', 'Historique des versions de chaque look'],
          image: '/images/outfit_recommendation_1791120459094.jpg',
          href: '/planner',
          cta: 'Planifier la semaine',
        },
        {
          id: 'discover',
          tab: 'Découvrir',
          title: 'Sélectionné, jamais saturé',
          text: 'Un flux sobre de pièces adaptées à votre garde-robe et votre budget, issues de maisons de confiance.',
          bullets: ['Seulement des pièces qui complètent un look', 'Accès privé aux revendeurs (Maison)', 'Enregistrer, comparer, ajouter à la liste'],
          image: '/images/wardrobe_leather_accessories.jpg',
          href: '/discover',
          cta: 'Commencer à découvrir',
        },
      ],
    },
    benefits: {
      label: 'Ce que vous obtenez',
      title: 'Des résultats, pas des fonctions.',
      items: [
        { icon: 'clock', title: 'Dix minutes gagnées chaque matin', text: 'Ouvrez l’app, voyez votre look, sortez.', metric: '-10 min / jour' },
        { icon: 'shirt', title: 'Une garde-robe plus active', text: 'Portez ce que vous possédez, pas seulement cinq pièces.', metric: '+38 % d’usage' },
        { icon: 'tag', title: 'Des achats plus justes', text: 'N’achetez que ce qui complète un look.', metric: '-27 % d’achats impulsifs' },
        { icon: 'sparkle', title: 'Une signature, pas une tendance', text: 'Un style cohérent qui dépasse la saison.', metric: '1 identité claire' },
        { icon: 'shield', title: 'Une confidentialité fiable', text: 'Vos photos et mesures vous appartiennent. Exportez ou supprimez à tout moment.', metric: '2FA + chiffrement' },
        { icon: 'globe', title: 'S’habiller partout', text: 'Recommandations adaptées au climat et à la culture.', metric: '190+ villes' },
      ],
    },
    how: {
      label: 'Comment ça marche',
      title: 'De la première photo au look final.',
      steps: [
        { n: '01', title: 'Dites-nous qui vous êtes', text: 'Un profil de style de cinq minutes : morphologie, palette, mode de vie et image souhaitée.' },
        { n: '02', title: 'Construisez votre garde-robe', text: 'Photographiez vos pièces. Nous identifions tissu, couleur et saison, et signalons les manques.' },
        { n: '03', title: 'Recevez vos looks', text: 'Chaque jour et pour chaque événement, Vastrié compose des tenues à partir de ce que vous possédez.' },
        { n: '04', title: 'Affinez et progressez', text: 'Notez les looks, ajoutez des pièces et consultez les rapports mensuels.' },
      ],
    },
    capabilities: {
      label: "L'atelier complet",
      title: 'Chaque capacité attendue — et davantage.',
      sub: 'Douze dimensions soignées du style personnel.',
      open: 'Explorer',
    },
    pricing: {
      label: 'Abonnements',
      title: 'Transparent. Résiliable à tout moment.',
      monthly: 'Mensuel',
      yearly: 'Annuel',
      save: '2 mois offerts',
      perMonth: '/ mois',
      perYear: '/ an',
      all: 'Comparer toutes les offres',
      featured: 'Le plus choisi',
    },
    proof: {
      label: 'Témoignages',
      title: 'Porté, approuvé, recommandé.',
      items: [
        { quote: 'J’ai enfin l’impression d’avoir un styliste qui connaît ma garde-robe mieux que moi.', name: 'Julien Marchetti', role: 'Associé, Marchetti & Co.' },
        { quote: 'Les capsules de voyage ont rentabilisé l’année. Un bagage cabine, six villes, jamais mal habillé.', name: 'Arnav Kapoor', role: 'Consultant en management' },
        { quote: 'C’est la retenue qui m’a convaincu. Pas de bruit, pas de tendances — un regard honnête.', name: 'Théo Lambert', role: 'Architecte' },
      ],
    },
    faq: {
      label: 'Questions',
      title: 'Avant de commencer.',
      items: [
        { q: 'Vastrié est-il vraiment gratuit au départ ?', a: 'Oui. Essentiel est gratuit : 40 pièces et trois recommandations IA par semaine. Passez à l’offre supérieure quand vous en avez besoin.' },
        { q: 'Dois-je photographier toute ma garde-robe ?', a: 'Non. Commencez par dix pièces. Vastrié devient utile immédiatement.' },
        { q: 'Que deviennent mes photos et mes données ?', a: 'Elles sont chiffrées, jamais vendues. Vous pouvez tout exporter ou supprimer depuis votre compte.' },
        { q: 'Puis-je résilier à tout moment ?', a: 'Oui, en un clic depuis Facturation. Vous gardez l’accès jusqu’à la fin de la période payée.' },
        { q: 'Est-ce uniquement pour les hommes ?', a: 'Vastrié est actuellement conçu pour l’homme. La mode féminine est prévue — rejoignez la liste d’attente.' },
      ],
    },
    cta: {
      title: 'Habillez-vous avec intention.',
      text: 'Inscription en moins d’une minute. Sans carte bancaire.',
      primary: "Entrer dans l'Atelier",
      secondary: 'Continuer en invité',
    },
    footer: {
      cols: [
        { title: 'Produit', links: [['Garde-robe', '/wardrobe'], ['Tenues', '/outfits'], ['Planificateur', '/planner'], ['Tarifs', '/pricing']] },
        { title: 'Découvrir', links: [['Notre histoire', '#story'], ['Journal', '/feed'], ['Centre d’aide', '/help'], ['Statut', '/maintenance']] },
        { title: 'Compte', links: [['Connexion', '/auth'], ['Paramètres', '/settings'], ['Facturation', '/billing'], ['Sécurité', '/settings/security']] },
        { title: 'Mentions Légales', links: [['Confidentialité', '/legal/privacy'], ['Conditions d’utilisation', '/legal/terms'], ['Cookies', '/legal/cookies']] },
      ],
      tag: 'Le maître du style personnel.',
    },
  },
};
